// An interface for abstracting event types. Categories are implemented here.
#pragma once
#include <memory>
#include "Object.h"

class IEvent {
public:

	enum EEventType : unsigned char {
		NONE = 0,
		FOCUS_GAINED,
		FOCUS_LOST,
		CLICKED,
		VALUE_CHANGED,
		SELECTION_CHANGED,
		STATE_CHANGED,
		VISIBILITY_CHANGED,
		ENABLED_CHANGED,
		TEXT_CHANGED,
		CURSOR_MOVED,
		CHILD_ADDED,
		CHILD_REMOVED,
		PARENT_UPDATED,
		LAYOUT_UPDATED,

		KEY_PRESSED,
		KEY_RELEASED
	};

	EEventType type{NONE};
	bool now{false}; // A very specific flag. I'll describe it in the handlers.

	IEvent() = default;
	virtual ~IEvent() = default; // C++ requires an interface to have at least one virtual method.
};

/*
The object event category.
Events such as changes to an object's focus, state, name, description, value, etc., always dispatch a CObjectEvent.
*/
class CObjectEvent final : public IEvent {
public:
	std::shared_ptr<IObject> object;
};

/*
The keyboard event category.
Key pressed and released events. always dispatch a CKeyboardEvent.
*/
class CKeyboardEvent final : public IEvent {
public:

	enum EKeycode : unsigned short {
		KEYCODE_A = 'A',
		KEYCODE_B = 'B',
		KEYCODE_C = 'C',
		KEYCODE_D = 'D',
		KEYCODE_E = 'E',
		KEYCODE_F = 'F',
		KEYCODE_G = 'G',
		KEYCODE_H = 'H',
		KEYCODE_I = 'I',
		KEYCODE_J = 'J',
		KEYCODE_K = 'K',
		KEYCODE_L = 'L',
		KEYCODE_M = 'M',
		KEYCODE_N = 'N',
		KEYCODE_O = 'O',
		KEYCODE_P = 'P',
		KEYCODE_Q = 'Q',
		KEYCODE_R = 'R',
		KEYCODE_S = 'S',
		KEYCODE_T = 'T',
		KEYCODE_U = 'U',
		KEYCODE_V = 'V',
		KEYCODE_W = 'W',
		KEYCODE_X = 'X',
		KEYCODE_Y = 'Y',
		KEYCODE_Z = 'Z',

		KEYCODE_0 = '0',
		KEYCODE_1 = '1',
		KEYCODE_2 = '2',
		KEYCODE_3 = '3',
		KEYCODE_4 = '4',
		KEYCODE_5 = '5',
		KEYCODE_6 = '6',
		KEYCODE_7 = '7',
		KEYCODE_8 = '8',
		KEYCODE_9 = '9',

		KEYCODE_F1 = 0x70,
		KEYCODE_F2,
		KEYCODE_F3,
		KEYCODE_F4,
		KEYCODE_F5,
		KEYCODE_F6,
		KEYCODE_F7,
		KEYCODE_F8,
		KEYCODE_F9,
		KEYCODE_F10,
		KEYCODE_F11,
		KEYCODE_F12,
		KEYCODE_F13,
		KEYCODE_F14,
		KEYCODE_F15,
		KEYCODE_F16,
		KEYCODE_F17,
		KEYCODE_F18,
		KEYCODE_F19,
		KEYCODE_F20,
		KEYCODE_F21,
		KEYCODE_F22,
		KEYCODE_F23,
		KEYCODE_F24,

		KEYCODE_UP = 0x26,
		KEYCODE_DOWN = 0x28,
		KEYCODE_LEFT = 0x25,
		KEYCODE_RIGHT = 0x27,
		KEYCODE_HOME = 0x24,
		KEYCODE_END = 0x23,
		KEYCODE_PAGE_UP = 0x21,
		KEYCODE_PAGE_DOWN = 0x22,
		KEYCODE_INSERT = 0x2D,
		KEYCODE_DELETE = 0x2E,

		KEYCODE_ESCAPE = 0x1B,
		KEYCODE_TAB = 0x09,
		KEYCODE_CAPS_LOCK = 0x14,
		KEYCODE_SHIFT = 0x10,
		KEYCODE_CTRL = 0x11,
		KEYCODE_ALT = 0x12,
		KEYCODE_SPACE = 0x20,
		KEYCODE_ENTER = 0x0D,
		KEYCODE_BACKSPACE = 0x08,

		KEYCODE_LEFT_SHIFT = 0xA0,
		KEYCODE_RIGHT_SHIFT = 0xA1,
		KEYCODE_LEFT_CTRL = 0xA2,
		KEYCODE_RIGHT_CTRL = 0xA3,
		KEYCODE_LEFT_ALT = 0xA4,
		KEYCODE_RIGHT_ALT = 0xA5,
		KEYCODE_LEFT_SUPER = 0x5B,
		KEYCODE_RIGHT_SUPER = 0x5C,
		KEYCODE_MENU = 0x5D,

		KEYCODE_NUMPAD_0 = 0x60,
		KEYCODE_NUMPAD_1,
		KEYCODE_NUMPAD_2,
		KEYCODE_NUMPAD_3,
		KEYCODE_NUMPAD_4,
		KEYCODE_NUMPAD_5,
		KEYCODE_NUMPAD_6,
		KEYCODE_NUMPAD_7,
		KEYCODE_NUMPAD_8,
		KEYCODE_NUMPAD_9,
		KEYCODE_NUMPAD_MULTIPLY,
		KEYCODE_NUMPAD_ADD,
		KEYCODE_NUMPAD_SEPARATOR,
		KEYCODE_NUMPAD_SUBTRACT,
		KEYCODE_NUMPAD_DECIMAL,
		KEYCODE_NUMPAD_DIVIDE,
		KEYCODE_NUMPAD_ENTER = 0xE0,

		KEYCODE_SCROLL_LOCK = 0x91,
		KEYCODE_NUM_LOCK = 0x90,
		KEYCODE_PAUSE = 0x13,

		KEYCODE_GRAVE = 0xC0,
		KEYCODE_MINUS = 0xBD,
		KEYCODE_EQUALS = 0xBB,
		KEYCODE_LEFT_BRACKET = 0xDB,
		KEYCODE_RIGHT_BRACKET = 0xDD,
		KEYCODE_BACKSLASH = 0xDC,
		KEYCODE_SEMICOLON = 0xBA,
		KEYCODE_APOSTROPHE = 0xDE,
		KEYCODE_COMMA = 0xBC,
		KEYCODE_PERIOD = 0xBE,
		KEYCODE_SLASH = 0xBF,

		KEYCODE_VOLUME_MUTE = 0xAD,
		KEYCODE_VOLUME_DOWN = 0xAE,
		KEYCODE_VOLUME_UP = 0xAF,
		KEYCODE_MEDIA_NEXT = 0xB0,
		KEYCODE_MEDIA_PREV = 0xB1,
		KEYCODE_MEDIA_STOP = 0xB2,
		KEYCODE_MEDIA_PLAY_PAUSE = 0xB3,

		KEYCODE_BROWSER_BACK = 0xA6,
		KEYCODE_BROWSER_FORWARD = 0xA7,
		KEYCODE_BROWSER_REFRESH = 0xA8,
		KEYCODE_BROWSER_STOP = 0xA9,
		KEYCODE_BROWSER_SEARCH = 0xAA,
		KEYCODE_BROWSER_FAVORITES = 0xAB,
		KEYCODE_BROWSER_HOME = 0xAC,

		KEYCODE_LAUNCH_MAIL = 0xB4,
		KEYCODE_LAUNCH_MEDIA_SELECT = 0xB5,
		KEYCODE_LAUNCH_APP1 = 0xB6,
		KEYCODE_LAUNCH_APP2 = 0xB7,

		KEYCODE_MOUSE_LEFT = 0x01,
		KEYCODE_MOUSE_RIGHT = 0x02,
		KEYCODE_MOUSE_MIDDLE = 0x04,
		KEYCODE_MOUSE_X1 = 0x05,
		KEYCODE_MOUSE_X2 = 0x06,

		KEYCODE_NONE = 0x00,
		KEYCODE_ANY = 0xFFFF
	};

	enum EModifier : unsigned char {
		MODIFIER_NONE = 0,
		MODIFIER_SHIFT = 1 << 0,
		MODIFIER_CTRL = 1 << 1,
		MODIFIER_ALT = 1 << 2,
		MODIFIER_SUPER = 1 << 3,
		MODIFIER_CAPS_LOCK = 1 << 4,
		MODIFIER_NUM_LOCK = 1 << 5
	};

	EKeycode keycode;
	unsigned char modifiers;
};

